DATASET:
  root_dataset: "/disk/vanishing_data/hj147/datasets/camera_lidar_semantic"
  dataset: "highway,urban"
  train_split: train
  val_split: val
  num_class: 11
  img_height: 480
  img_width: 640

MODEL:
  arch: "frrnA"
  expert: "moe_joint"         # two decoders jointly update
  shared_encoder: True
  gate: "classwise_w_conv"   # "simple_wo_conv"
  with_conv: True

SYSTEM:
  num_workers: 4
  pin_memory: False

TRAIN:
  start_epoch: 0
  num_epochs: 100
  patience: 100
  num_epochs_ft: 20
  patience_ft: 20
  eval_interval: 2
  batch_size: 2
  optimizer: "SGD"
  lr: 0.0001
  momentum: 0.99
  weight_decay: 0.0001
  lr_schedule: "cos"
  seed: 304
  resume: ""

VAL:
  batch_size: 1
  visualize: False
  checkpoint: "model_best.pth"

TEST:
  batch_size: 8
  img_height: 960
  img_width: 1280

DIR: "run/"
