DATASET:
  root_dataset: "/disk/ml/datasets/aev/camera_lidar_semantic"
  dataset: "highway,urban"
  train_split: train
  val_split: val
  num_class: 38
  img_height: 480
  img_width: 640

MODEL:
  arch: "frrnA"
  expert: "moe"
  gate: "classwise_w_conv"   # "simple_wo_conv"
  with_conv: True
  shared_encoder: False

SYSTEM:
  num_workers: 4
  pin_memory: False

TRAIN:
  start_epoch: 0
  num_epochs: 30
  patience: 20
  eval_interval: 2
  batch_size: 8
  optimizer: "SGD"
  lr: 0.01
  momentum: 0.99
  weight_decay: 0.0001
  lr_schedule: "cos"
  seed: 304
  resume: ""

VAL:
  batch_size: 1
  visualize: False
  checkpoint: "model_best.pth"

TEST:
  batch_size: 1

DIR: "/disk/vanishing_data/pavlitsk/moe_experiments/experts/audi_split/"
test_sets: ['all']
delta_path: "/disk/vanishing_data/pavlitsk/moe_experiments/attacks/20240818_101508_frrn_moe_classwise_w_conv_True_dataset_all_pdg_epsilon_0.05_steps_10/delta/delta_30.pt"
epsilon: 0.1
pgd_steps: 10
output_dir: "/disk/vanishing_data/pavlitsk/moe_experiments/attacks/"
train_dataset: 'all'
